package db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import db.Usuarios;
import db.Lugares;

import db.UsuariosDao;
import db.LugaresDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig usuariosDaoConfig;
    private final DaoConfig lugaresDaoConfig;

    private final UsuariosDao usuariosDao;
    private final LugaresDao lugaresDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        usuariosDaoConfig = daoConfigMap.get(UsuariosDao.class).clone();
        usuariosDaoConfig.initIdentityScope(type);

        lugaresDaoConfig = daoConfigMap.get(LugaresDao.class).clone();
        lugaresDaoConfig.initIdentityScope(type);

        usuariosDao = new UsuariosDao(usuariosDaoConfig, this);
        lugaresDao = new LugaresDao(lugaresDaoConfig, this);

        registerDao(Usuarios.class, usuariosDao);
        registerDao(Lugares.class, lugaresDao);
    }
    
    public void clear() {
        usuariosDaoConfig.clearIdentityScope();
        lugaresDaoConfig.clearIdentityScope();
    }

    public UsuariosDao getUsuariosDao() {
        return usuariosDao;
    }

    public LugaresDao getLugaresDao() {
        return lugaresDao;
    }

}
