package db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import db.Usuarios;

import db.UsuariosDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig usuariosDaoConfig;

    private final UsuariosDao usuariosDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        usuariosDaoConfig = daoConfigMap.get(UsuariosDao.class).clone();
        usuariosDaoConfig.initIdentityScope(type);

        usuariosDao = new UsuariosDao(usuariosDaoConfig, this);

        registerDao(Usuarios.class, usuariosDao);
    }
    
    public void clear() {
        usuariosDaoConfig.clearIdentityScope();
    }

    public UsuariosDao getUsuariosDao() {
        return usuariosDao;
    }

}
