package db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "USUARIOS".
 */
@Entity
public class Usuarios {

    @Id(autoincrement = true)
    private Long id_user;
    private String usu_nombre;

    @Unique
    private String usu_nick;
    private String usu_fecha;
    private String usu_email;
    private String usu_password;

    @Generated
    public Usuarios() {
    }

    public Usuarios(Long id_user) {
        this.id_user = id_user;
    }

    @Generated
    public Usuarios(Long id_user, String usu_nombre, String usu_nick, String usu_fecha, String usu_email, String usu_password) {
        this.id_user = id_user;
        this.usu_nombre = usu_nombre;
        this.usu_nick = usu_nick;
        this.usu_fecha = usu_fecha;
        this.usu_email = usu_email;
        this.usu_password = usu_password;
    }

    public Long getId_user() {
        return id_user;
    }

    public void setId_user(Long id_user) {
        this.id_user = id_user;
    }

    public String getUsu_nombre() {
        return usu_nombre;
    }

    public void setUsu_nombre(String usu_nombre) {
        this.usu_nombre = usu_nombre;
    }

    public String getUsu_nick() {
        return usu_nick;
    }

    public void setUsu_nick(String usu_nick) {
        this.usu_nick = usu_nick;
    }

    public String getUsu_fecha() {
        return usu_fecha;
    }

    public void setUsu_fecha(String usu_fecha) {
        this.usu_fecha = usu_fecha;
    }

    public String getUsu_email() {
        return usu_email;
    }

    public void setUsu_email(String usu_email) {
        this.usu_email = usu_email;
    }

    public String getUsu_password() {
        return usu_password;
    }

    public void setUsu_password(String usu_password) {
        this.usu_password = usu_password;
    }

}
